### ISSUE TITLE
Setting 화면(+ 결제수단, 카테고리 작성 화면) Component 정리 및 세부 기능 구현하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-accountbook-12#35]
### 📌 내용
Setting화면과 결제수단, 수입/지출 카테고리 작성화면 Component 분리 및 세부 기능 추가 구현하기

### 🛠 ToDo
- [x] 결제 수단 입력 화면 Component 분리하기
- [x] 수입/지출 카테고리 입력화면 Component 분리하기
- [x] 설정 화면 Component 분리하기
- [x] 결제 수단 입력 시, 이름 중복 체크
- [x] 수입/지출 입력 시, 이름 중복 체크
- [x] 이름이 중복일 시 snackbar로 알려주기
- [x] 결제수단, 수입/지출 입력 시, soft keyboard에 의해 버튼이 가려지는거 수정

**Comment by aurora32s** [comment]
#### [참고 문서 🛠]
[Snackbar in Compose](https://www.devbitsandbytes.com/configuring-snackbar-jetpack-compose-using-scaffold-with-bottom-navigation/)
