### ISSUE TITLE
Navigation 이슈 수정하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-accountbook-12#36]
### 📌 내용
각 페이지에서 DB에 새로운 데이터를 추가하고, 이전 화면으로 돌아가는 도중 recomposition이 여러번 발생하는 문제가 발생
이를 수정하여 데이터 추가 이후 이전 화면으로 정상 이동하고 추가된 데이터가 화면에 반영되도록 수정 필요

### 🛠 ToDo
- [x] 결제 수단 추가
- [x] 수입/지출 카테고리 추가
- [x] 수입/지출 내역 추가

**Comment by aurora32s** [comment]
#### [참고 자료 🛠]
[jetpack compose에서 여러 side effect 관리하기](https://medium.com/mobile-app-development-publication/jetpack-compose-side-effects-made-easy-a4867f876928)
