### ISSUE TITLE
Graph 화면 및 Detail 화면의 Component 정리 및 세부 사항 구현 완료하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-accountbook-12#39]
### 📌 내용
Graph화면과 Detail 화면의 Component 정리 및 세부적인 구현 사항 완료하기!

### 🛠 ToDo
- [x] Detail 화면의 Component 정리하기
- [x] Graph 화면의 Component 정리하기
- [x] Detail 화면에서 이전 화면으로 돌아갈 때 연도/월 유지하기
- [x] 이전 화면으로 돌아오면 유지된 연도/월에 해당하는 데이터 불러오기

**Comment by aurora32s** [comment]
- [ ] 화면 회전 시, 그래프와 리스트 위치 변경해주기
[참고 stackoverflow](https://stackoverflow.com/questions/64753944/orientation-on-jetpack-compose)
