### ISSUE TITLE
내역 관련 화면 Component 정리 및 세부 사항 구현

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-accountbook-12#43]
### 📌 내용
내역 화면(history 화면)과 내역 작성 화면(post 화면) component 정리 및 세부 사항 구현하기

### 🛠 ToDo
- [x] 내역 화면(history 화면)의 Component 정리하기
- [x] default tab은 수입/지출 모두 선택
- [x] 연도/월을 달력 화면 / 통계 화면과 연동
- [x] 내역 작성 화면(post 화면)의 Component 정리하기
- [x] 가로 전환 시, 입력란이 버튼에 가려지지 않도록 스크롤 기능 추가하기 
   + 가로 전환 시, soft 키보드에 가려지는 문제는 pass
- [x] 결제 수단, 수입/지출 카테고리 추가 후, 내역 작성 화면으로 돌아왔을 때 결제 수단, 수입/지출 카테고리 재호출하기
- [x] 수입일 경우, 입금 수단도 작성할 수 있도록 하기
   + method와 같은 테이블에서 관리하기
