### ISSUE TITLE
Hilt 적용하면서 DataLayer 코드 정리하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-accountbook-12#45]
### 📌 내용
Hilt 적용하고 viewModel - repository - data source 단 코드 정리 및 navigation 코드 정리

### 🛠 ToDo
- [x] 내역 리스트 화면 코드 정리
- [x] 내역 작성 화면 코드 정리
- [x] 달력 화면 코드 정리
- [x] 통계 화면 코드 정리
- [x] 카테고리별 상세 지출 내역 코드 정리
- [x] 설정 화면 코드 정리
- [x] 결제수단/입금계좌 코드 정리
- [x] 수입/지출 카테고리 코드 정리
- [x] Hilt 적용
- [x] navigation 단 코드 정리

**Comment by aurora32s** [comment]
시작하자마자 에러에 부딪혔습니다. 😭
java.lang.reflect.InvocationTargetException (no error message)

자료를 찾아보니, Hilt와 Kotlin의 버전이 맞지 않아 발생한 문제라고 하네요...
[참고 자료 1](https://stackoverflow.com/questions/67744002/hilt-unsupported-metadata-version-in-kotlin)
