### ISSUE TITLE
Firebase App 출시하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android-accountbook-12#48]
### 📌 내용
Firebase에 App 출시해보기

### 🛠 ToDo
- [ ] Firebase App 출시하기
- [ ] 엑셀에 관련 내용 작성하기

**Comment by aurora32s** [comment]
### [이슈 수정]
- [ ] sub destination 에서는 pop stack이 시작 화면이 아닌 이전 화면으로 이동
- [ ] 수입/지출 금액 작성 시 formatting에 의해 커서가 앞으로 이동하는 이슈 수정

**Comment by aurora32s** [comment]
#### [참고 문서 🔥]
[Filtering and modifying text input in Jetpack Compose way](https://blog.shreyaspatil.dev/filtering-and-modifying-text-input-in-jetpack-compose-way)
